version: '3.8'

services:
  rtms-mock:
    build: .
    ports:
      - "9092:9092"  # Handshake server
      - "8081:8081"  # Media server
      - "3000:3000"  # Webhook server
    volumes:
      - ./data:/usr/src/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped 